"""Buridan UI Anatomy Registry.

AUTO-GENERATED by scripts/generate_anatomy.py -- do not edit by hand.
Edit the corresponding file in app/www/anatomy_src/ instead, then re-run the script.
"""

ANATOMY = {
    "accordion": """accordion.root(
    accordion.item(
        accordion.trigger(),
        accordion.panel(),
    ),
    accordion.item(
        accordion.trigger(),
        accordion.panel(),
    ),
)""",
    "attachment": """attachment.root(
    attachment.media(),
    attachment.content(
        attachment.title(),
        attachment.description(),
    ),
    attachment.actions(
        attachment.action()
    ),
)""",
    "avatar": """avatar.root(
    avatar.image(),
    avatar.fallback(),
)""",
    "badge": """badge()""",
    "bubble": """bubble.root(
    bubble.content(),
    bubble.reactions(),
)""",
    "button": """button()""",
    "button_group": """button_group.root(
    button(),
    button_group.separator(),
)""",
    "card": """card.root(
    card.header(
        card.title(),
        card.description(),
        card.action(),
    ),
    card.content(),
    card.footer(),
)""",
    "checkbox": """checkbox.root(
    checkbox.indicator(),
)""",
    "dialog": """dialog.root(
    dialog.trigger(),
    dialog.popup(
        dialog.title(),
        dialog.description(),
        dialog.close(),
    ),
)""",
    "field": """field.root(
    field.content(
        field.label(),
        field.title(),
        field.description(),
    ),
    field.error(),
)""",
    "frame": """frame.root(
    frame.panel(
        frame.header(
            frame.title(),
            frame.description(),
        ),
        frame.footer(),
    ),
)""",
    "input": """input()""",
    "input_group": """input_group.root(
    input_group.input(placeholder="Search..."),
    input_group.addon(),
)""",
    "marker": """marker.root(
    marker.icon(),
    marker.content(),
)""",
    "menu": """menu.root(
    menu.trigger(),
    menu.content(
        menu.group_label(),
        menu.item(menu.shortcut()),
        menu.separator(),
        menu.group_label(),
        menu.close(),
    ),
)""",
    "message": """message.group(
    message.root(
        message.avatar(),
        message.content(
            message.header(),
            message.footer(),
        ),
    ),
)""",
    "select": """select(
    select.option(),
    select.optgroup(
        select.option(),
        select.option(),
    ),
    select.optgroup(
        select.option(),
        select.option(),
    ),
)""",
    "separator": """separator()""",
    "spinner": """spinner()""",
    "switch": """switch.root()""",
    "tabs": """tabs.root(
    tabs.list(
        tabs.trigger(),
    ),
    tabs.content(),
)""",
    "textarea": """textarea()""",
}
