"""Buridan UI Component Registry.

AUTO-GENERATED by scripts/generate_registry.py -- do not edit by hand.
Re-run the script after adding/moving/renaming component files.
"""

COMPONENT_REGISTRY = {
    # --- components/chart ---
    "chart_tooltip": {
        "files": ["components/chart/chart_tooltip.py"],
        "dependencies": [],
    },

    # --- components/core ---
    "core": {
        "files": ["components/core/core.py"],
        "dependencies": [],
    },
    "hugeicon": {
        "files": ["components/core/hugeicon.py"],
        "dependencies": ["core"],
    },

    # --- components/ui ---
    "accordion": {
        "files": ["components/ui/accordion.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "attachment": {
        "files": ["components/ui/attachment.py"],
        "dependencies": ["button", "core"],
    },
    "avatar": {
        "files": ["components/ui/avatar.py"],
        "dependencies": ["core"],
    },
    "badge": {
        "files": ["components/ui/badge.py"],
        "dependencies": ["core"],
    },
    "bubble": {
        "files": ["components/ui/bubble.py"],
        "dependencies": ["core"],
    },
    "button": {
        "files": ["components/ui/button.py"],
        "dependencies": ["core"],
    },
    "button_group": {
        "files": ["components/ui/button_group.py"],
        "dependencies": ["core", "separator"],
    },
    "card": {
        "files": ["components/ui/card.py"],
        "dependencies": ["core"],
    },
    "checkbox": {
        "files": ["components/ui/checkbox.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "dialog": {
        "files": ["components/ui/dialog.py"],
        "dependencies": ["core"],
    },
    "field": {
        "files": ["components/ui/field.py"],
        "dependencies": ["separator"],
    },
    "frame": {
        "files": ["components/ui/frame.py"],
        "dependencies": ["core"],
    },
    "input": {
        "files": ["components/ui/input.py"],
        "dependencies": ["core"],
    },
    "input_group": {
        "files": ["components/ui/input_group.py"],
        "dependencies": ["button", "core", "input", "textarea"],
    },
    "marker": {
        "files": ["components/ui/marker.py"],
        "dependencies": ["core"],
    },
    "menu": {
        "files": ["components/ui/menu.py"],
        "dependencies": ["core"],
    },
    "message": {
        "files": ["components/ui/message.py"],
        "dependencies": ["core"],
    },
    "select": {
        "files": ["components/ui/select.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "separator": {
        "files": ["components/ui/separator.py"],
        "dependencies": ["core"],
    },
    "spinner": {
        "files": ["components/ui/spinner.py"],
        "dependencies": ["core"],
    },
    "switch": {
        "files": ["components/ui/switch.py"],
        "dependencies": ["core"],
    },
    "tabs": {
        "files": ["components/ui/tabs.py"],
        "dependencies": ["core"],
    },
    "textarea": {
        "files": ["components/ui/textarea.py"],
        "dependencies": ["core"],
    },
}
