# _PROSE_CLASS = (
#     "prose-li:marker:text-foreground "
#     "prose-code:before:content-none "
#     "prose-code:after:content-none "
#     "prose-code:rounded-lg "
#     "prose dark:prose-invert max-w-none w-full "
#     "prose-h1:scroll-mt-14 prose-h2:scroll-mt-14 "
#     "prose-h1:text-2xl prose-h1:font-bold prose-h1:tracking-tight prose-h1:mb-3 "
#     "prose-h2:text-xl prose-h2:font-semibold prose-h2:tracking-tight prose-h2:mt-6 prose-h2:mb-3 "
#     "prose-p:text-muted-foreground prose-p:leading-relaxed "
#     "prose-code:bg-muted prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-sm "
#     # --- BLOCKQUOTES ---
#     "prose-blockquote:w-full "
#     "[&>blockquote>p]:text-sm "
#     "[&>blockquote>p]:font-light "
#     "[&>blockquote>p]:text-foreground "
#     "prose-blockquote:bg-secondary dark:prose-blockquote:bg-card "
#     "prose-blockquote:flex "
#     "prose-blockquote:px-3 "
#     "prose-blockquote:not-italic "
#     "prose-blockquote:border-0 "
#     "prose-blockquote:before:content-none "
#     "prose-blockquote:after:content-none "
#     "[&>blockquote>p]:before:content-none "
#     "[&>blockquote>p]:after:content-none "
#     # Code blocks
#     "prose-pre:rounded-2xl "
#     "prose-pre:text-md "
#     "prose-pre:bg-secondary dark:prose-pre:bg-card "
#     "prose-pre:shadow-none "
#     "prose-pre:border-0 "
#     "prose-pre:p-0 "
#     "prose-pre:my-4 "
#     "prose-pre:overflow-x-auto "
#     # Remove Typography's backticks on code blocks
#     "prose-pre:before:content-none "
#     "prose-pre:after:content-none "
#     # Code inside <pre>
#     "prose-pre:font-normal "
#     "[&>pre>code]:block "
#     "[&>pre>code]:px-4 "
#     "[&>pre>code]:py-4 "
#     # "[&>pre>code]:text-[13px] "
#     "[&>pre>code]:bg-transparent "
#     # Wrapper
#     "[&>div>table]:w-max "
#     "[&>div>table]:min-w-full "
#     # Table
#     "prose-table:border "
#     "prose-table:border-input "
#     "prose-table:rounded-[1rem] "
#     "prose-table:mb-4 "
#     # Header
#     "prose-thead:border-b "
#     "prose-thead:border-input "
#     "prose-th:px-4 prose-th:py-2 "
#     "prose-th:text-left prose-th:font-bold "
#     "prose-th:whitespace-nowrap "
#     # Body
#     "prose-tbody:divide-y "
#     "prose-tbody:divide-input "
#     # Cells
#     "prose-td:px-4 prose-td:py-2 "
#     "prose-td:whitespace-nowrap "
# )
