"""
Preset codec — ported directly from theme-preview.js (the actual, tested
encoder your web theme builder uses), NOT reconstructed from scratch. The
CLI has to decode exactly what the browser tool produces, so this needs to
match bit-for-bit, not just be "a reasonable scheme." Verified against real
codes generated by theme-preview.js — see conversation for the interop test.

Encoding: a single packed integer —
  bits 28-31: format version (currently 2)
  bits 23-26: style index      (direct list index, 0-based)
  bits 19-22: radius index     (0 = inherit from style; N = radii[N-1])
  bits 15-18: base index       (direct list index, 0-based)
  bits 10-14: color index      (0 = inherit from base;  N = colors[N-1])
  bits  5-9:  chart index      (0 = inherit from color/base; N = colors[N-1])
  bits  0-4:  font index       (direct list index, 0-based)
— base62-encoded. "b0" is a reserved literal for the all-defaults preset,
not something that round-trips through the bit-packer.

Version 1 (legacy) codes are still decodable — they predate the "chart"
dimension, which defaults to "inherit" for any v1 code. Encoding always
uses the current version; only decoding needs to understand the old one.
"""

BASE62_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
DEFAULT_PRESET_CODE = "b0"
PRESET_VERSION = 2

BITS_V1 = {"font": 5, "color": 5, "base": 4, "radius": 4, "style": 4}
BITS_V2 = {"font": 5, "color": 5, "chart": 5, "base": 4, "radius": 4, "style": 4}


def _compute_shifts(bits: dict, order: list[str]) -> dict:
    shifts = {}
    offset = 0
    for name in order:
        shifts[name] = offset
        offset += bits[name]
    return shifts


SHIFT_V1 = _compute_shifts(BITS_V1, ["font", "color", "base", "radius", "style"])
SHIFT_V2 = _compute_shifts(
    BITS_V2, ["font", "color", "chart", "base", "radius", "style"]
)


def decode_base62(s: str) -> int | None:
    num = 0
    for ch in s:
        idx = BASE62_ALPHABET.find(ch)
        if idx == -1:
            return None
        num = num * 62 + idx
    return num


def _mask(width: int) -> int:
    return (1 << width) - 1


def decode_seed(
    seed: str,
    base_themes: list[dict],
    color_themes: list[dict],
    style_registry: list[dict],
    radii_options: list[dict],
    font_registry: list[dict],
) -> dict | None:
    """
    Returns: baseId, colorId, chartId, styleId, fontId, radius.
    colorId/chartId are None when inheriting. radius is None when
    inheriting from the active style's own --radius — NOT a hardcoded
    literal — since "b0" means "everything default, including the style's
    own native radius," not "override radius to some fixed value."
    """
    if not seed:
        return None

    if seed == DEFAULT_PRESET_CODE:
        packed = PRESET_VERSION << 28
    else:
        packed = decode_base62(seed)
        if packed is None:
            return None

    version = (packed >> 28) & 0xF

    if version == 1:
        shift, bits = SHIFT_V1, BITS_V1
        chart_idx = 0  # v1 codes predate the chart dimension — always inherit
    elif version == 2:
        shift, bits = SHIFT_V2, BITS_V2
        chart_idx = (packed >> shift["chart"]) & _mask(bits["chart"])
    else:
        return None  # unknown future version — reject rather than misread

    style_idx = (packed >> shift["style"]) & _mask(bits["style"])
    radius_idx = (packed >> shift["radius"]) & _mask(bits["radius"])
    base_idx = (packed >> shift["base"]) & _mask(bits["base"])
    color_idx = (packed >> shift["color"]) & _mask(bits["color"])
    font_idx = (packed >> shift["font"]) & _mask(bits["font"])

    if (
        base_idx >= len(base_themes)
        or style_idx >= len(style_registry)
        or font_idx >= len(font_registry)
    ):
        return None

    color_id = (
        color_themes[color_idx - 1]["id"]
        if 0 < color_idx <= len(color_themes)
        else None
    )
    chart_id = (
        color_themes[chart_idx - 1]["id"]
        if 0 < chart_idx <= len(color_themes)
        else None
    )
    radius_value = (
        radii_options[radius_idx - 1]["value"]
        if 0 < radius_idx <= len(radii_options)
        else None
    )

    return {
        "baseId": base_themes[base_idx]["id"],
        "colorId": color_id,
        "chartId": chart_id,
        "styleId": style_registry[style_idx]["id"],
        "fontId": font_registry[font_idx]["id"],
        "radius": radius_value,
    }
